version: "3.7"

services:
    filebeat:
        user: root
        container_name: filebeat
        image: docker.elastic.co/beats/filebeat:7.7.1
        restart: always
        volumes:
          - /home/logstah/filebeat.docker.yml:/usr/share/filebeat/filebeat.yml
          - /home/logstah/log/node.INFO:/filebeat/log/node.INFO
          - /home/logstah/registry:/usr/share/filebeat/data/registry
        networks:
          - localnet
        depends_on:
          - redis


    redis:
        user: root
        container_name: redis
        image: redis:latest
        restart: always
        ports:
          - 6379:6379
        command: redis-server /etc/conf/redis.conf
        volumes:
          - /home/logstah/redis/data:/data
          - /home/logstah/redis/conf:/etc/conf
        privileged: true
        environment:
          - TZ=Asia/Shanghai
          - LANG=en_US.UTF-8
        networks:
          - localnet
          
          
          
#配置网络，注意记得创建docker网络
networks:
  localnet:
    external:
      name: localnet